#!/bin/bash
compile () {
    echo "gcc -Wall -fPIC -c $debug \"$1.c\" -I../balloons"
    gcc -Wall -fPIC -c $debug "$1.c" -I../balloons
    if [[ $? -ne 0 ]]; then
        exit
    fi
    echo "gcc -shared \"-Wl,-install_name,$1.so\" -o \"$1.so\" \"$1.o\" ../build/*.o -lcurl"
    gcc -shared "-Wl,-install_name,$1.so" -o "$1.so" "$1.o" ../build/*.o -lcurl
}

cd $(dirname $0)

debug=""
while getopts "d" opt; do
    case $opt in
        d)
            debug="-g"
            shift
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit
            ;;
    esac
done

for file in $(ls); do
case $file in
*.c) compile ${file%.c};;
*);;
esac
done


